[project]
name = "semantic search engine"
version = "0.1.0"
description = ""
authors = [ {name = "My Name", email = "myemail@example.com"}, ]
requires-python = ">= 3.12"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"